name: Upload Changed Files to Release

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로 실행

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Get changed files
      id: changed_files
      run: |
        git fetch origin main
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          echo "Only one commit in history, getting all files."
          git diff --name-only HEAD > changed_files.txt
        else
          git diff --name-only HEAD~1 HEAD > changed_files.txt
        fi

    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME="release-$(date +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)"
        CHANGED_FILES=$(cat changed_files.txt)
        echo "Changed files:"
        echo "$CHANGED_FILES"
        gh release create "$TAG_NAME" --title "Release $TAG_NAME" --notes "Automated release created by GitHub Actions.
        
        Changed files:
        $CHANGED_FILES"

    - name: Upload Changed Files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=$(gh release view --json tagName -q .tagName)
        for file in $(cat changed_files.txt); do
          echo "Uploading $file"
          gh release upload "$TAG_NAME" "$file"
        done
      shell: bash
