name: Upload Changed Files to Release

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 워크플로 실행

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Create Release
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.LHS }}
      run: |
        TAG_NAME="release-$(date +'%Y%m%d%H')"
        gh release create $TAG_NAME --title "Release $TAG_NAME" --notes "Automated release created by GitHub Actions."

    - name: Get changed files
      id: changed_files
      run: |
        git fetch origin main
        git diff --name-only HEAD^ HEAD > changed_files.txt

    - name: Upload Changed Files
      env:
        GITHUB_TOKEN: ${{ secrets.LHS }}
      run: |
        TAG_NAME=$(gh release view --json tagName -q .tagName)
        for file in $(cat changed_files.txt); do
          echo "Uploading $file"
          gh release upload $TAG_NAME "$file"
        done
      shell: bash
