name: Upload Changed Files to Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install GitHub CLI
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt update
        sudo apt install gh -y

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.LHS }}
      with:
        tag_name: v1.0.0
        release_name: "Release v1.0.0"
        draft: false
        prerelease: false

    - name: Get changed files
      id: changed_files
      run: |
        git fetch origin main
        git diff --name-only HEAD^ HEAD > changed_files.txt

    - name: Upload Changed Files
      env:
        GITHUB_TOKEN: ${{ secrets.LHS }}
      run: |
        for file in $(cat changed_files.txt); do
          echo "Uploading $file"
          gh release upload ${{ steps.create_release.outputs.upload_url }} "$file"
        done
      shell: bash
